#################################################################################
#
#   This is the package for NWS ALERTS USING THE CUSTOM COMPONENT
#
#   This is for use with the default sensor entity_id created with the integration version 6 or later 
#
#################################################################################

## For testing the API

# https://api.weather.gov/alerts/active/count

# https://api.weather.gov/alerts/active?zone=INZ009,INC033

######################## BINARY SENSOR  #########################################

binary_sensor:
  - platform: template
    sensors:
      nws_alerts_are_active:
        friendly_name: NWS Alerts Are Active
        value_template: >
          {{ states('sensor.nws_alerts_alerts') | int(0) > 0 }}
        icon_template: >-
          {% if states('sensor.nws_alerts_alerts') | int(0) > 0 %}
            mdi:weather-lightning
          {% else %}
            mdi:weather-sunny
          {% endif %}
      

########################  AUTOMATION  ###########################################

automation:

  - alias: NWS - Mobile App Notifications
    id: nws_mobile_app_notifications
    trigger:
      - platform: state
        entity_id: sensor.nws_alerts_alerts
    condition:
      - condition: numeric_state
        entity_id: sensor.nws_alerts_alerts
        above: 0
    action:
      - repeat:
          sequence:
            - service: script.turn_on
              continue_on_error: true
              entity_id: script.notification_pushover_message
              data:
                variables:
                  target: my_phone
                  message: "NWS New: {{ repeat.item.Event }}"
                  sound: echo
            - delay:
                seconds: 5
          for_each: "{{ trigger.to_state.attributes.Alerts | reject('in', trigger.from_state.attributes.Alerts) | sort(attribute='ID') | list() }}"
    mode: queued
    initial_state: "on"
    max: 10         

###############################################################################

  - alias: NWS - Persistent Notifications
    id: nws_persistent_notifications
    trigger:
      - platform: state
        entity_id: sensor.nws_alerts_alerts
    condition: 
      - condition: numeric_state
        entity_id: sensor.nws_alerts_alerts
        above: 0
    action:
      - repeat:
          sequence:
            - service: script.nws_alerts_persistent_notification
              data:
                notification_id: "NWS_{{ repeat.item.ID }}"
                title: "NWS New: {{ repeat.item.Event }}"
                message: "{{ repeat.item.Description }}"
            - delay:
                seconds: 5
          for_each: "{{ trigger.to_state.attributes.Alerts | reject('in', trigger.from_state.attributes.Alerts) | sort(attribute='ID') | list() }}"
    mode: queued
    initial_state: "on"
    max: 10

###############################################################

## I am using the Alexa Media Player custom integration to play the announcement. If you don't use that integration you may have to adjust the service call for your system.

## lastly, I am calling two different scripts for announcements - one for very dangerous weather (i.e. tornoados) that will play throughtout the house including the bedrooms
## and a different one for everything else that won't wake people up for, for example, a heat advisory.
## modify this to your desired requirements.
    
  - alias: NWS - TTS Announcements
    id: nws_tts_announcements
    description: ""
    trigger:
      - platform: state
        entity_id: sensor.nws_alerts_alerts
    condition:
      - condition: numeric_state
        entity_id: sensor.nws_alerts_alerts
        above: 0
    action:
      - repeat:
          sequence:
            - variables:
                alert: "{{ repeat.item }}"
            - if:
                - condition: template
                  value_template: "{{ ('Tornado Warning' in alert.Event) and (alert.Type == 'Alert') }}"
              then:
                - service: script.turn_on
                  entity_id: script.nws_alerts_announce_tornado_warning
                - delay:
                    minutes: 1
          for_each: "{{ trigger.to_state.attributes.Alerts | reject('in', trigger.from_state.attributes.Alerts) | list() | sort(attribute='ID') }}"
      - repeat:
          sequence:
            - variables:
                alert: "{{ repeat.item }}"
            - if:
                - condition: template
                  value_template: "{{ ('Severe Thunderstorm Warning' in alert.Event) and (alert.Type == 'Alert') }}"
              then:
                - service: script.turn_on
                  entity_id: script.nws_alerts_announce_thunderstorm_warning
                - delay:
                    minutes: 1
          for_each: "{{ trigger.to_state.attributes.Alerts | reject('in', trigger.from_state.attributes.Alerts) | list() | sort(attribute='ID') }}"
    mode: queued
    initial_state: "on"
    max: 10

#################################  SCRIPT  ###################################

script:
  nws_alerts_persistent_notification:
    alias: NWS Alerts Persistent Notifications
    sequence:
      - service: >
          {% if states('sensor.nws_alerts_alerts') != '0' %}
            persistent_notification.create
          {% endif %}
        data:
          notification_id: "{{ notification_id }}"
          message: "{{ message }}"
          title: '{{ title }}'

  nws_alerts_announce_tornado_warning:
    alias: NWS Alerts Announce Tornado Warning
    sequence:
      # Set volume for Alexa devices
      - service: media_player.volume_set
        data:
          entity_id:
            - media_player.bathroom_show
          volume_level: 0.9
      
      # Set volume for Google devices
      - service: media_player.volume_set
        data:
          entity_id:
            - media_player.speaker_great_room
          volume_level: 0.9      
      # First announcement with OpenAI TTS on Google devices
      - service: tts.speak
        data:
          cache: true
          message: "Attention! Attention! The National Weather Service Has issued a tornado warning for our area."
          entity_id: tts.openai_tts_shimmer
          media_player_entity_id: 
            - media_player.speaker_great_room
      # First announcement with Alexa devices
      - service: notify.alexa_media
        data:
          target: 
            - media_player.bathroom_show
          data:
            type: tts
          message: Attention!,,,Attention!,,,The National Weather Service Has issued a tornado warning for our area.
      
      # Delay before alert tone
      - delay: '00:00:15'
      
      # Alert tone on Google devices
      - service: media_player.play_media
        data:
          entity_id:
            - media_player.speaker_great_room
          media_content_id: "https://your_remote_access.ui.nabu.casa/local/mp3/nws_alert_tone.mp3"
          media_content_type: music
      
      # Alert tone on Alexa devices
      - service: notify.alexa_media
        data:
          message: "<audio src='https://your_remote_access.ui.nabu.casa/local/mp3/nws_alert_tone.mp3' />"
          target: 
            - media_player.bathroom_show
          data:
            type: tts
      
      # Delay before second announcement
      - delay: '00:00:25'
      
      # Second announcement with OpenAI TTS on Google devices
      - service: tts.speak
        data:
          cache: true
          message: "Attention! Attention! The National Weather Service Has issued a tornado warning for our area."
          entity_id: tts.openai_tts_shimmer
          media_player_entity_id: 
            - media_player.speaker_great_room
      
      # Second announcement with Alexa devices
      - service: notify.alexa_media
        data:
          target: 
            - media_player.bathroom_show
          data:
            type: tts
          message: Attention!,,,Attention!,,,The National Weather Service Has issued a tornado warning for our area.

  nws_alerts_announce_thunderstorm_warning:
    alias: NWS Alerts Announce Thunderstorm Warning  
    sequence:
      # Set volume for Alexa devices
      - service: media_player.volume_set
        data:
          entity_id:
            - media_player.bathroom_show
          volume_level: 0.9
      
      # Set volume for Google devices
      - service: media_player.volume_set
        data:
          entity_id:
            - media_player.speaker_great_room
          volume_level: 0.9
      
      # First announcement with OpenAI TTS on Google devices
      - service: tts.speak
        data:
          cache: true
          message: "Attention! Attention! The National Weather Service Has issued a severe thunderstorm warning for our area."
          entity_id: tts.openai_tts_shimmer
          media_player_entity_id: 
            - media_player.speaker_great_room

      # First announcement with Alexa devices
      - service: notify.alexa_media
        data:
          target: 
            - media_player.bathroom_show
          data:
            type: tts
          message: Attention!,,,Attention!,,,The National Weather Service Has issued a severe thunderstorm warning for our area.
      
      # Delay before alert tone
      - delay: '00:00:15'
      
      # Alert tone on Google devices
      - service: media_player.play_media
        data:
          entity_id:
            - media_player.speaker_great_room
          media_content_id: "https://your_remote_access.ui.nabu.casa/local/mp3/nws_alert_tone.mp3"
          media_content_type: music
      
      # Alert tone on Alexa devices
      - service: notify.alexa_media
        data:
          message: "<audio src='https://your_remote_access.ui.nabu.casa/local/mp3/nws_alert_tone.mp3' />"
          target: 
            - media_player.bathroom_show
          data:
            type: tts
      
      # Delay before second announcement
      - delay: '00:00:25'
      
      # Second announcement with OpenAI TTS on Google devices
      - service: tts.speak
        data:
          cache: true
          message: "Attention! Attention! The National Weather Service Has issued a severe thunderstorm warning for our area."
          entity_id: tts.openai_tts_shimmer
          media_player_entity_id: 
            - media_player.speaker_great_room
      
      # Second announcement with Alexa devices
      - service: notify.alexa_media
        data:
          target: 
            - media_player.bathroom_show
          data:
            type: tts
          message: Attention!,,,Attention!,,,The National Weather Service Has issued a severe thunderstorm warning for our area.
